# Generated by Django 3.1.1 on 2020-11-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_name', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=50, unique=True)),
                ('sub_type', models.CharField(choices=[('reg', 'Regular'), ('sel', 'Selective')], max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroommodel')),
                ('handled_by', models.ForeignKey(limit_choices_to=models.Q(('user_type', 2), ('user_type', 3), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
