# Generated by Django 3.1.1 on 2020-11-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(
                fields=('sub_name', 'classroom'), name='unique_sub_per_class'),
        ),
    ]
