# Generated by Django 3.1.1 on 2020-11-19 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0003_auto_20201119_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 4}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
