# Generated by Django 3.1.1 on 2020-11-20 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0004_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='handled_by',
            field=models.ForeignKey(limit_choices_to=models.Q(user_type=2), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 3}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
