# Generated by Django 3.1.1 on 2021-01-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20201214_1442'),
        ('subject', '0007_auto_20201126_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hour_type', models.CharField(choices=[('reg', 'Regular'), ('sel', 'Selective')], max_length=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='subjectmodel',
            name='unique_sub_per_class',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='hour_name',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='hourmodel',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroommodel'),
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.hourmodel'),
        ),
    ]
