# Generated by Django 3.1.1 on 2021-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_auto_20210126_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmodel',
            name='hour_type',
            field=models.CharField(choices=[('reg', 'Regular'), ('sel', 'Selective'), ('lab', 'Lab')], max_length=10),
        ),
    ]
