# Generated by Django 3.1.1 on 2021-03-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_auto_20210126_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourmodel',
            options={'verbose_name': 'Hour', 'verbose_name_plural': 'Hours'},
        ),
    ]
