# Generated by Django 3.1.1 on 2021-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_auto_20210414_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourmodel',
            name='semester',
            field=models.CharField(choices=[(1, 'Semester I'), (2, 'Semester II'), (3, 'Semester III'), (4, 'Semester IV'), (5, 'Semester V'), (6, 'Semester VI')], default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='sub_code',
            field=models.CharField(default=19, max_length=15),
            preserve_default=False,
        ),
    ]
