# Generated by Django 3.1.1 on 2021-05-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_auto_20210502_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmodel',
            name='semester',
            field=models.CharField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI')], max_length=20),
        ),
    ]
