# Generated by Django 3.2 on 2023-12-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('reject', 'Reject'), ('cancel', 'Cancel'), ('calloff', 'Call Off')], max_length=10)),
                ('hour', models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')])),
            ],
            options={
                'verbose_name': 'AttendanceID',
                'verbose_name_plural': 'AttendancesIDs',
                'db_table': 'attendanceID',
            },
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendancess.attendanceidmodel')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
            },
        ),
    ]
