# Generated by Django 3.1.1 on 2020-11-27 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('handled_by', models.CharField(max_length=150)),
                ('status', models.CharField(blank=True, choices=[('reject', 'Reject'), ('cancel', 'Cancel'), ('calloff', 'Call Off')], max_length=10)),
                ('student', models.ManyToManyField(limit_choices_to={'user_type': 3}, related_name='student_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
            },
        ),
    ]
