# Generated by Django 3.1.1 on 2020-12-07 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20201126_1825'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendancess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancemodel',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='attendancemodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendancemodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='attendance_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='rollno',
            field=models.CharField(default='18BCM552', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('handled_by', models.CharField(max_length=150)),
                ('status', models.CharField(blank=True, choices=[('reject', 'Reject'), ('cancel', 'Cancel'), ('calloff', 'Call Off')], max_length=10)),
                ('student', models.ManyToManyField(limit_choices_to={'user_type': 3}, related_name='student_attendance', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmodel')),
            ],
            options={
                'verbose_name': 'AttendanceID',
                'verbose_name_plural': 'AttendancesIDs',
                'db_table': 'attendanceID',
            },
        ),
    ]
