# Generated by Django 3.1.1 on 2020-12-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancess', '0002_auto_20201207_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceidmodel',
            name='handled_by',
        ),
    ]
