# Generated by Django 3.1.1 on 2020-12-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancess', '0003_remove_attendanceidmodel_handled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceidmodel',
            name='student',
        ),
    ]
