# Generated by Django 3.1.1 on 2021-03-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_auto_20210325_0704'),
        ('attendancess', '0005_attendanceidmodel_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceidmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.hourmodel'),
        ),
    ]
