# Generated by Django 3.1.1 on 2021-03-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancess', '0006_auto_20210325_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceidmodel',
            old_name='subject',
            new_name='hour_fk',
        ),
    ]
