# Generated by Django 3.1.1 on 2021-03-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_auto_20210325_0704'),
        ('attendancess', '0007_auto_20210325_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceidmodel',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmodel'),
            preserve_default=False,
        ),
    ]
