# Generated by Django 3.1.1 on 2021-04-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendancess', '0009_attendanceidmodel_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendancess.attendanceidmodel'),
        ),
    ]
