# Generated by Django 3.1.1 on 2021-05-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancess', '0010_auto_20210411_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI')])),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Day Order',
                'verbose_name_plural': 'Day Orders',
                'db_table': 'dayorder',
            },
        ),
        migrations.CreateModel(
            name='LeaveDateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Leave Date',
                'verbose_name_plural': 'Leave Dates',
                'db_table': 'leavedate',
            },
        ),
    ]
