# Generated by Django 3.1.1 on 2020-11-19 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[(1, 'I'), (2, 'II'), (3, 'III')], max_length=5)),
                ('sec', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=5, null=True)),
                ('timetable', models.CharField(blank=True, max_length=5, null=True)),
                ('tutor', models.ForeignKey(limit_choices_to=models.Q(('user_type', 2), ('user_type', 3), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
