# Generated by Django 3.1.1 on 2020-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommodel',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')]),
        ),
    ]
