# Generated by Django 3.2 on 2023-12-09 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommodel',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'user_type': 3}, related_name='classroom_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
