# Generated by Django 3.1.1 on 2020-11-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201119_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroommodel',
            name='timetable',
        ),
    ]
