# Generated by Django 3.1.1 on 2020-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_classroommodel_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommodel',
            name='sec',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=5, null=True),
        ),
    ]
