# Generated by Django 3.1.1 on 2020-11-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20201120_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroommodel',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
    ]
