# Generated by Django 3.1.1 on 2020-11-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20201126_1825'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classroommodel',
            table='classroom',
        ),
    ]
