# Generated by Django 3.1.1 on 2020-12-14 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0007_auto_20201126_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommodel',
            name='students',
            field=models.ManyToManyField(related_name='classroom_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
