# Generated by Django 3.1.1 on 2021-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20201214_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommodel',
            name='batch',
            field=models.CharField(default=2018, max_length=10),
            preserve_default=False,
        ),
    ]
