# Generated by Django 3.2 on 2023-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')])),
                ('sec', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classroom',
            },
        ),
    ]
