# Generated by Django 3.2 on 2023-12-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('attendancess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceidmodel',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classroom.classroommodel'),
        ),
    ]
