# Generated by Django 3.1.1 on 2020-11-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0003_remove_classroommodel_timetable'),
        ('subject', '0004_subject_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=50)),
                ('hour', models.PositiveSmallIntegerField()),
                ('day', models.CharField(max_length=15)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroommodel')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
            ],
        ),
    ]
