# Generated by Django 3.1.1 on 2020-11-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20201125_0935'),
        ('classroom', '0005_auto_20201120_1922'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeTable',
            new_name='TimetableModel',
        ),
    ]
