# Generated by Django 3.1.1 on 2020-11-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20201125_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetablemodel',
            options={'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetables'},
        ),
    ]
