# Generated by Django 3.1.1 on 2020-11-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20201126_2041'),
        ('timetable', '0004_auto_20201126_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablemodel',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='sub',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TimetablesetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroommodel')),
            ],
            options={
                'verbose_name': 'Timetable Set',
                'verbose_name_plural': 'Timetable Sets',
                'db_table': 'timetableset',
            },
        ),
    ]
