# Generated by Django 3.1.1 on 2020-11-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20201127_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetablesetmodel',
            options={'verbose_name': 'Set', 'verbose_name_plural': 'Sets'},
        ),
        migrations.RenameField(
            model_name='timetablemodel',
            old_name='sub',
            new_name='subject',
        ),
        migrations.AlterModelTable(
            name='timetablesetmodel',
            table='Set',
        ),
    ]
