# Generated by Django 3.1.1 on 2020-11-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20201127_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='set_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablesetmodel'),
        ),
    ]
