# Generated by Django 3.1.1 on 2020-11-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20201127_2003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetablesetmodel',
            table='set',
        ),
    ]
