# Generated by Django 3.1.1 on 2020-12-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20201126_1825'),
        ('timetable', '0008_auto_20201127_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='hour',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectmodel'),
        ),
    ]
