# Generated by Django 3.1.1 on 2020-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20201204_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='day',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=15),
        ),
    ]
