# Generated by Django 3.1.1 on 2020-12-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20201207_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='hour',
            field=models.CharField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], max_length=3),
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='set_name',
            field=models.ForeignKey(help_text='Create a set if your set is not in the choice list', on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablesetmodel'),
        ),
    ]
