# Generated by Django 3.1.1 on 2020-12-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_auto_20201211_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='hour',
            field=models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')]),
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='set_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablesetmodel'),
        ),
    ]
