# Generated by Django 3.1.1 on 2021-03-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_auto_20210126_1806'),
        ('timetable', '0016_auto_20210107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.hourmodel'),
        ),
    ]
