# Generated by Django 3.1.1 on 2021-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20210324_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI')]),
        ),
    ]
