# Generated by Django 3.1.1 on 2021-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20210414_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesetmodel',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
