# Generated by Django 3.1.1 on 2020-11-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_staffmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterModelTable(
            name='staffmodel',
            table='staff',
        ),
    ]
