# Generated by Django 3.1.1 on 2020-11-28 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_delete_staffmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(user_type=2), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'db_table': 'staff',
            },
        ),
    ]
